/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator;

/**
 *
 * @author Lemogang Moloko
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    
    //Declarations
    double NumEnter1;
    double NumEnter2;
    double Result;
    String Op;
    
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextResult = new javax.swing.JTextField();
        jbtnCE = new javax.swing.JButton();
        jbtnBS = new javax.swing.JButton();
        jbtnPM = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtnDigit8 = new javax.swing.JButton();
        jbtnDigit7 = new javax.swing.JButton();
        jbtnDigitPlus = new javax.swing.JButton();
        jbtnDigit9 = new javax.swing.JButton();
        jbtnDigit5 = new javax.swing.JButton();
        jbtnDigit4 = new javax.swing.JButton();
        jbtnDigitMinus = new javax.swing.JButton();
        jbtnDigit6 = new javax.swing.JButton();
        jbtnDigit2 = new javax.swing.JButton();
        jbtnDigit1 = new javax.swing.JButton();
        jbtnDigitMultiplication = new javax.swing.JButton();
        jbtnDigit3 = new javax.swing.JButton();
        jbtnDigitDot = new javax.swing.JButton();
        jbtnDigit0 = new javax.swing.JButton();
        jbtnDigitEqual = new javax.swing.JButton();
        jbtnDigitDivision = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextResult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextResultActionPerformed(evt);
            }
        });
        getContentPane().add(jTextResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 40));

        jbtnCE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnCE.setText("CE");
        jbtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCEActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 70, 40));

        jbtnBS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnBS.setText("←");
        jbtnBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBSActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, 40));

        jbtnPM.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPM.setText("±");
        jbtnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPMActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 70, 40));

        jbtnC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 70, 40));

        jbtnDigit8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigit8.setText("8");
        jbtnDigit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit8ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 70, 40));

        jbtnDigit7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigit7.setText("7");
        jbtnDigit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit7ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, 40));

        jbtnDigitPlus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigitPlus.setText("+");
        jbtnDigitPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigitPlusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigitPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 70, 40));

        jbtnDigit9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigit9.setText("9");
        jbtnDigit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit9ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 70, 40));

        jbtnDigit5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigit5.setText("5");
        jbtnDigit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 70, 40));

        jbtnDigit4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigit4.setText("4");
        jbtnDigit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 70, 40));

        jbtnDigitMinus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigitMinus.setText("-");
        jbtnDigitMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigitMinusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigitMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 70, 40));

        jbtnDigit6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigit6.setText("6");
        jbtnDigit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 70, 40));

        jbtnDigit2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigit2.setText("2");
        jbtnDigit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 70, 40));

        jbtnDigit1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigit1.setText("1");
        jbtnDigit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 70, 40));

        jbtnDigitMultiplication.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigitMultiplication.setText("X");
        jbtnDigitMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigitMultiplicationActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigitMultiplication, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 70, 40));

        jbtnDigit3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigit3.setText("3");
        jbtnDigit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 70, 40));

        jbtnDigitDot.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigitDot.setText(".");
        jbtnDigitDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigitDotActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigitDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 70, 40));

        jbtnDigit0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigit0.setText("0");
        jbtnDigit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit0ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 70, 40));

        jbtnDigitEqual.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigitEqual.setText("=");
        jbtnDigitEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigitEqualActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigitEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 70, 40));

        jbtnDigitDivision.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDigitDivision.setText("/");
        jbtnDigitDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigitDivisionActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigitDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 70, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //
    private void EnterNumbers(String q)
    {
    String Nums = jTextResult.getText() + q;
    jTextResult.setText(Nums);
    }
    
    
    private void jTextResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextResultActionPerformed

    private void jbtnDigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit1ActionPerformed
        EnterNumbers("1");
    }//GEN-LAST:event_jbtnDigit1ActionPerformed

    private void jbtnDigitMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigitMinusActionPerformed
        NumEnter1 = Double.parseDouble(jTextResult.getText());
        jTextResult.setText("");
        Op = "-";
    }//GEN-LAST:event_jbtnDigitMinusActionPerformed
//setting btn Backspace
    private void jbtnBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBSActionPerformed
       String Backspace = null;
       
       if(jTextResult.getText().length() > 0)
       {
           StringBuilder sb = new StringBuilder(jTextResult.getText());
           sb.deleteCharAt(jTextResult.getText().length() - 1);
           Backspace = sb.toString();
           jTextResult.setText(Backspace);
       }
    }//GEN-LAST:event_jbtnBSActionPerformed
//setting btn 7
    private void jbtnDigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit7ActionPerformed
        EnterNumbers("7");
    }//GEN-LAST:event_jbtnDigit7ActionPerformed
//setting btn 8
    private void jbtnDigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit8ActionPerformed
        EnterNumbers("8");
    }//GEN-LAST:event_jbtnDigit8ActionPerformed
//setting btn 9
    private void jbtnDigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit9ActionPerformed
        EnterNumbers("9");
    }//GEN-LAST:event_jbtnDigit9ActionPerformed
//setting btn 4
    private void jbtnDigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit4ActionPerformed
        EnterNumbers("4");
    }//GEN-LAST:event_jbtnDigit4ActionPerformed
//setting btn 5
    private void jbtnDigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit5ActionPerformed
        EnterNumbers("5");
    }//GEN-LAST:event_jbtnDigit5ActionPerformed
//setting btn 6
    private void jbtnDigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit6ActionPerformed
        EnterNumbers("6");
    }//GEN-LAST:event_jbtnDigit6ActionPerformed
//setting btn 2
    private void jbtnDigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit2ActionPerformed
        EnterNumbers("2");
    }//GEN-LAST:event_jbtnDigit2ActionPerformed
//setting btn 3
    private void jbtnDigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit3ActionPerformed
        EnterNumbers("3");
    }//GEN-LAST:event_jbtnDigit3ActionPerformed
//setting btn 0
    private void jbtnDigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit0ActionPerformed
        EnterNumbers("0");
    }//GEN-LAST:event_jbtnDigit0ActionPerformed
//setting the division operator
    private void jbtnDigitDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigitDivisionActionPerformed
        NumEnter1 = Double.parseDouble(jTextResult.getText());
        jTextResult.setText("");
        Op = "/";
    }//GEN-LAST:event_jbtnDigitDivisionActionPerformed
//setting the multiplication operator
    private void jbtnDigitMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigitMultiplicationActionPerformed
        NumEnter1 = Double.parseDouble(jTextResult.getText());
        jTextResult.setText("");
        Op = "*";
    }//GEN-LAST:event_jbtnDigitMultiplicationActionPerformed
//setting the addition operator
    private void jbtnDigitPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigitPlusActionPerformed
        NumEnter1 = Double.parseDouble(jTextResult.getText());
        jTextResult.setText("");
        Op = "+";
    }//GEN-LAST:event_jbtnDigitPlusActionPerformed
//setting the Clear btn
    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
       jTextResult.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed
//setting the CE btn
    private void jbtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCEActionPerformed
        jTextResult.setText("");
        
        String Fn,Sn;
        
        Fn = String.valueOf(NumEnter1);
        Sn = String.valueOf(NumEnter2);
        
        Fn = "";
        Sn = "";
    }//GEN-LAST:event_jbtnCEActionPerformed

    //setting the negative and positive btn
    private void jbtnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPMActionPerformed
    double nums = Double.parseDouble(String.valueOf(jTextResult.getText()));
    nums = nums * (-1);
    jTextResult.setText(String.valueOf(nums));
    }//GEN-LAST:event_jbtnPMActionPerformed
//setting the dot btn
    private void jbtnDigitDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigitDotActionPerformed
       if(! jTextResult.getText().contains("."))
       {
       jTextResult.setText(jTextResult.getText() + jbtnDigitDot.getText());
       }
    }//GEN-LAST:event_jbtnDigitDotActionPerformed
//setting the equal to btn
    private void jbtnDigitEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigitEqualActionPerformed
      NumEnter2 = Double.parseDouble(jTextResult.getText());
      if(Op == "+")
      {
      Result = NumEnter1 + NumEnter2;
      jTextResult.setText(String.valueOf(Result));
      }
      
      else if(Op == "-")
      {
      Result = NumEnter1 - NumEnter2;
      jTextResult.setText(String.valueOf(Result));
      }
      
      else if(Op == "*")
      {
      Result = NumEnter1 * NumEnter2;
      jTextResult.setText(String.valueOf(Result));
      }
      
      else if(Op == "/")
      {
      Result = NumEnter1 / NumEnter2;
      jTextResult.setText(String.valueOf(Result));
      }
    }//GEN-LAST:event_jbtnDigitEqualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextResult;
    private javax.swing.JButton jbtnBS;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnCE;
    private javax.swing.JButton jbtnDigit0;
    private javax.swing.JButton jbtnDigit1;
    private javax.swing.JButton jbtnDigit2;
    private javax.swing.JButton jbtnDigit3;
    private javax.swing.JButton jbtnDigit4;
    private javax.swing.JButton jbtnDigit5;
    private javax.swing.JButton jbtnDigit6;
    private javax.swing.JButton jbtnDigit7;
    private javax.swing.JButton jbtnDigit8;
    private javax.swing.JButton jbtnDigit9;
    private javax.swing.JButton jbtnDigitDivision;
    private javax.swing.JButton jbtnDigitDot;
    private javax.swing.JButton jbtnDigitEqual;
    private javax.swing.JButton jbtnDigitMinus;
    private javax.swing.JButton jbtnDigitMultiplication;
    private javax.swing.JButton jbtnDigitPlus;
    private javax.swing.JButton jbtnPM;
    // End of variables declaration//GEN-END:variables
}


//Lemogang Moloko